"""Precomputed Newton-Schulz coefficient table for Muon.

This module is the runtime source of truth for coefficient lookup. The table is
prepared offline, stored here, and imported into memory before any optimizer
steps run. No coefficient search or disk loading is performed inside the
optimizer step.
"""

# Reference coefficient sets.
STANDARD_NS = (1.500, -0.500, 0.000)
JORDAN_NS = (3.445, -4.775, 2.032)
FAST_NS = (3.867, -4.400, 1.399)  # found by find_fast_coeffs()
FAST_NS_TABLE_KEY = 3.87
STRICT_FALLBACK_TABLE_KEY = 3.62
STRICT_FALLBACK_NS = (3.624985, -7.285039, 4.444867)


# STRICT_FALLBACK_NS is the current non-Jordan fallback endpoint for the
# FastNS-to-safe one-parameter table schedule. It is the existing 3.62 table
# entry, chosen because its scalar map has lower overshoot than FastNS while the
# table entries visited by an a-only schedule remain strict-band stable.

# The entries below 3.50 are conservative Muon/Jordan reference points. The
# dense high-a tail is generated by scripts/build_coeff_table.py using the
# strict 5-iteration band criterion.
MUON_COEFF_TABLE = {
    1.50: STANDARD_NS,
    2.00: (2.000000, -1.500000, 0.500000),
    2.50: (2.500000, -2.500000, 1.000000),
    3.00: (3.000000, -3.500000, 1.500000),
    3.44: JORDAN_NS,
    3.50: (3.504903, -5.416326, 2.581007),
    3.51: (3.514951, -6.301005, 3.390634),
    3.52: (3.524824, -3.239247, 0.832264),
    3.53: (3.534997, -6.925304, 4.015659),
    3.54: (3.544872, -4.368870, 1.641147),
    3.55: (3.554957, -6.049051, 3.099595),
    3.56: (3.564896, -4.430912, 1.631734),
    3.57: (3.574920, -5.798498, 2.738437),
    3.58: (3.584959, -7.154037, 4.215608),
    3.59: (3.594649, -3.918534, 1.207550),
    3.60: (3.604981, -4.174041, 1.367648),
    3.61: (3.614998, -4.291026, 1.453560),
    3.62: (3.624985, -7.285039, 4.444867),
    3.63: (3.634988, -6.048568, 2.949597),
    3.64: (3.644736, -4.864497, 1.875808),
    3.65: (3.654910, -7.166951, 4.198321),
    3.66: (3.664904, -3.934291, 1.211228),
    3.67: (3.674956, -6.694930, 3.589661),
    3.68: (3.684981, -6.457985, 3.290305),
    3.69: (3.694600, -4.827842, 1.844920),
    3.70: (3.704955, -5.013037, 1.959526),
    3.71: (3.714865, -6.168584, 3.026451),
    3.72: (3.724991, -4.677121, 1.726531),
    3.73: (3.734801, -4.404906, 1.493883),
    3.74: (3.744339, -6.786169, 3.585220),
    3.75: (3.754967, -4.415155, 1.500234),
    3.76: (3.764792, -4.964795, 1.874038),
    3.77: (3.774546, -4.111265, 1.275985),
    3.78: (3.784400, -5.869900, 2.632320),
    3.79: (3.794781, -4.141896, 1.267738),
    3.80: (3.804957, -5.029750, 1.910739),
    3.81: (3.813739, -5.289838, 2.100016),
    3.82: (3.824097, -4.606668, 1.575301),
    3.83: (3.834916, -4.784392, 1.679057),
    3.84: (3.844685, -4.331734, 1.363614),
    3.85: (3.854563, -4.458193, 1.457326),
    3.86: (3.864922, -4.535393, 1.489271),
    3.87: FAST_NS,
    3.88: (3.882773, -4.569776, 1.506182),
    3.89: (3.886044, -4.449237, 1.424091),
}

# Backwards-compatible alias used by tests and older scripts.
DEFAULT_COEFF_TABLE = MUON_COEFF_TABLE


def get_muon_coeff_table():
    """Return a copy of the precomputed in-memory Muon coefficient table."""
    return dict(MUON_COEFF_TABLE)


def get_muon_coeff_lookup():
    """Return precomputed sorted keys and values for fast lookup."""
    return MUON_COEFF_KEYS, MUON_COEFF_VALUES


# Pre-indexed in-memory lookup arrays. These are built once at import time and
# reused by AdaptiveMuon instances for fast nearest-lower lookup.
MUON_COEFF_KEYS = tuple(sorted(MUON_COEFF_TABLE))
MUON_COEFF_VALUES = tuple(MUON_COEFF_TABLE[key] for key in MUON_COEFF_KEYS)
